name: FloatingTips
author: lorenzo.stanco
category: Interface
tags: [tip, tooltip, balloon, tips]
demo: http://jsfiddle.net/yAWDT/30/
docs: http://wiki.github.com/lorenzos/FloatingTips/docs
current: 2.0