name: FloatingTips
author: lorenzo.stanco
category: Interface
tags: [tip, tooltip, balloon, tips]
demo: http://jsfiddle.net/yAWDT/176/
docs: http://wiki.github.com/lorenzos/FloatingTips/docs
current: 2.1
sources: "Source/floatingtips.js"